import uuid
import hashlib

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class FarmerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone_number = models.CharField(max_length=15, unique=True)
    preferred_language = models.CharField(max_length=10, default='hi')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.phone_number}"

class FarmerMemory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='memories')
    item_type = models.CharField(max_length=50) # 'fertilizer', 'manure', 'irrigation'
    item_name = models.CharField(max_length=255)
    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.item_name} ({self.item_type})"


class OTPChallenge(models.Model):
    """Short-lived, one-use verification challenge. Never persist the OTP itself."""
    phone_hash = models.CharField(max_length=64, db_index=True)
    otp_hash = models.CharField(max_length=128)
    requested_ip = models.GenericIPAddressField(null=True, blank=True)
    expires_at = models.DateTimeField(db_index=True)
    attempts = models.PositiveSmallIntegerField(default=0)
    consumed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    @staticmethod
    def hash_phone(phone_number):
        return hashlib.sha256(phone_number.encode("utf-8")).hexdigest()


class Farm(models.Model):
    id = models.AutoField(primary_key=True)

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="farms"
    )

    name = models.CharField(max_length=100)

    crop_type = models.CharField(
        max_length=100
    )

    latitude = models.DecimalField(
        max_digits=9,
        decimal_places=6
    )

    longitude = models.DecimalField(
        max_digits=9,
        decimal_places=6
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.name


class SensorNode(models.Model):
    id = models.AutoField(primary_key=True)

    farm = models.ForeignKey(
        Farm,
        on_delete=models.CASCADE,
        related_name="sensor_nodes"
    )

    node_id = models.CharField(
        max_length=100,
        unique=True
    )

    name = models.CharField(
        max_length=100,
        blank=True
    )

    is_active = models.BooleanField(
        default=True
    )

    registered_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ["-registered_at"]

    def __str__(self):
        return self.node_id


class SensorReading(models.Model):
    id = models.AutoField(primary_key=True)

   
    client_uuid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False
    )

    sensor_node = models.ForeignKey(
        SensorNode,
        on_delete=models.CASCADE,
        related_name="readings"
    )

    temperature = models.FloatField(
        null=True,
        blank=True
    )

    humidity = models.FloatField(
        null=True,
        blank=True
    )

    soil_moisture = models.FloatField(
        null=True,
        blank=True
    )

    # Rain since the preceding reading, in millimetres. Required by tomato risk rules.
    rainfall_mm = models.FloatField(default=0.0)

    recorded_at = models.DateTimeField(
        default=timezone.now,
        db_index=True
    )

    class Meta:
        ordering = ["-recorded_at"]

        constraints = [
            models.UniqueConstraint(
                fields=["sensor_node", "recorded_at"],
                name="unique_reading_per_node_time"
            )
        ]

    def __str__(self):
        return f"{self.sensor_node.node_id} - {self.recorded_at}"


class TreatmentRecommendation(models.Model):
    id = models.AutoField(primary_key=True)

    disease = models.CharField(
        max_length=100,
        unique=True
    )

    description_en = models.TextField()

    description_hi = models.TextField(
        blank=True
    )

    description_pa = models.TextField(
        blank=True
    )

    description_bn = models.TextField(
        blank=True
    )

    description_ta = models.TextField(
        blank=True
    )

    source = models.CharField(
        max_length=255,
        blank=True
    )

    def __str__(self):
        return self.disease


class DiseasePrediction(models.Model):
    id = models.AutoField(primary_key=True)

    # UUID generated by the client for offline-sync deduplication.
    client_uuid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False
    )

    farm = models.ForeignKey(
        Farm,
        on_delete=models.CASCADE,
        related_name="disease_predictions"
    )

    sensor_reading = models.ForeignKey(
        SensorReading,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="disease_predictions"
    )

    treatment = models.ForeignKey(
        TreatmentRecommendation,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="predictions"
    )

    image = models.ImageField(
        upload_to="disease_images/%Y/%m/%d/"
    )

    predicted_label = models.CharField(
        max_length=100
    )

    confidence = models.FloatField()

    top_3_predictions = models.JSONField(
        null=True,
        blank=True
    )

    predicted_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True
    )

    was_helpful = models.BooleanField(
        null=True,
        blank=True
    )

    class Meta:
        ordering = ["-predicted_at"]

    def __str__(self):
        return (
            f"{self.farm.name} - "
            f"{self.predicted_label} "
            f"({self.confidence:.2f})"
        )


class RiskScore(models.Model):

    RISK_BANDS = [
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
    ]

    id = models.AutoField(primary_key=True)

    farm = models.ForeignKey(
        Farm,
        on_delete=models.CASCADE,
        related_name="risk_scores"
    )

    treatment = models.ForeignKey(
        TreatmentRecommendation,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="risk_scores"
    )

    disease = models.CharField(
        max_length=100
    )

    score = models.FloatField()

    band = models.CharField(
        max_length=10,
        choices=RISK_BANDS
    )

    window_start = models.DateTimeField(
        null=True,
        blank=True
    )

    window_end = models.DateTimeField(
        null=True,
        blank=True
    )

    calculated_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True
    )

    class Meta:
        ordering = ["-calculated_at"]

    def __str__(self):
        return (
            f"{self.farm.name} - "
            f"{self.disease}: "
            f"{self.score} ({self.band})"
        )
